//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee_detail
    {
 
        public int Id { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Phone_Number { get; set; }
        public string Address { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> Age { get; set; }
        
    }
}
